import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation/Navigation';
import { Montserrat } from 'next/font/google';
import { useRouter } from 'next/router';

const montserrat = Montserrat({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-primary', // będzie dostępny w css pod tą zmienną
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const router = useRouter();
	const isAdminRoute = router.pathname.startsWith('/admin');

	return (
		<html lang="en">
			<body className={inter.className}>
				{isAdminRoute === true ? <Navigation /> : null}
				<Navigation />
				{children}
			</body>
		</html>
	);
}
