import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from '@/components/Navigation/Navigation';
import { Montserrat } from 'next/font/google';
import { useRouter, usePathname } from 'next/navigation';

const montserrat = Montserrat({
	weight: '400',
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-primary', // będzie dostępny w css pod tą zmienną
});

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Navigation />
				{children}
			</body>
		</html>
	);
}
